ALTER TABLE song
    ADD album_id BIGINT;

ALTER TABLE song
    ADD CONSTRAINT FK_SONG_ON_ALBUM FOREIGN KEY (album_id) REFERENCES album (id);

ALTER TABLE genre
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE album
    ALTER COLUMN uuid DROP NOT NULL;

ALTER TABLE artist
    ALTER COLUMN uuid DROP NOT NULL;

ALTER TABLE genre
    ALTER COLUMN uuid DROP NOT NULL;